name: trash_themes
description: Trash is a well written collection of flutter packages to speed up the developing process.
version: 0.0.2
homepage: https://github.com/vincenzopalazzo/trash

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

