name: changelog

ide:
  intellij: true

packages:
  - packages/**

scripts:
  analyze:
    run: melos exec -c 1 -- "dart format --set-exit-if-changed . && flutter analyze . --fatal-infos"
    description: Run dart analyzer in a specific package.
    select-package:

  component_analyze:
    run: melos exec -c 1 --scope="trash_component" -- "dart format --set-exit-if-changed . && dart analyze . --fatal-infos"
    description: Run dart analyzer in a specific package.

  trash_analyze:
    run: melos exec -c 1 --scope="trash_themes" -- "dart format --set-exit-if-changed . && flutter analyze . --fatal-infos"
    description: Run dart analyzer in a specific package.

  component_test:
    description: Run tests in a specific package.
    run: melos exec --concurrency=2 --scope="trash_component" -- "flutter pub get && dart pub run test"
    env:
      MELOS_TEST: true

  trash_test:
    description: Run tests in a specific package.
    run: melos exec --concurrency=2 --scope="trash_themes" -- "flutter pub get && dart pub run test"
    env:
      MELOS_TEST: true

  build_examples:
    description: Build the plugin used inside the tests.
    run: melos exec --concurrency=2 --scope="cln_plugin" -- "make examples"
    env:
      MELOS_TEST: true


  format: dart format -o write .
