name: trash_theme Dart Code sanity check

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: |
          cd packages/themes
          flutter pub get
      - run: |
          cd packages/themes
          flutter format --set-exit-if-changed .
      - run: |
          cd packages/themes
          flutter analyze .